import { useParams, Link } from 'react-router-dom';
import { useState, useEffect } from 'react';
import { Download, Info, ArrowLeft, ShieldAlert, Fingerprint, ListChecks, ExternalLink } from 'lucide-react';
import { downloadReport, getAnalysisById } from '../services/analysisApi';
import { categorizeIoc } from '../utils/iocCategorization';
import { SeverityBadge } from '../components/common/SeverityBadge';
import { Panel } from '../components/common/Panel';

type AnyRecord = Record<string, any>;

export default function AnalysisResult() {
  const { id } = useParams(); const [analysis, setAnalysis] = useState<AnyRecord | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<Record<string, boolean>>({ reasoning: true, authentication: true, attackChain: true, findings: true, iocs: true, raw: false });
  useEffect(() => { if (!id) return; getAnalysisById(id).then(setAnalysis).catch(() => setError('Failed to load analysis. Ensure backend is running.')).finally(() => setLoading(false)); }, [id]);
  if (loading) return <LoadingState />;
  if (error || !analysis) return <div className="mx-auto max-w-5xl rounded border border-red-800/60 bg-red-950/30 p-5 text-sm text-red-300">{error || 'Analysis not found.'}</div>;

  const authentication = analysis.authentication || {}; const findings = Array.isArray(analysis.forensic_findings) ? analysis.forensic_findings : []; const iocs = extractedIocs(analysis); const attackChain = Array.isArray(analysis.attack_chain_steps) ? analysis.attack_chain_steps : [];
  const toggle = (key: string) => setExpanded(current => ({ ...current, [key]: !current[key] }));
  const verdict = String(analysis.verdict || 'unknown'); const risk = Number(analysis.risk_score || 0);

  return <div className="mx-auto max-w-[1500px] space-y-5">
    <header className="flex flex-col gap-4 border-b border-[#151D28] pb-5 lg:flex-row lg:items-end lg:justify-between"><div><Link to="/history" className="mb-3 inline-flex items-center gap-1.5 text-xs text-gray-500 transition-colors hover:text-cyan-300"><ArrowLeft size={13} /> Return to history</Link><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-cyan-500">Digital forensics report</p><h1 className="mt-1 break-all font-mono text-lg font-semibold text-white">{analysis.analysis_id}</h1><p className="mt-1 max-w-3xl text-sm text-gray-500">{analysis.subject || 'Untitled email'} <span className="mx-1 text-gray-700">·</span> {analysis.sender || 'Sender unavailable'} <span className="mx-1 text-gray-700">·</span> {formatDate(analysis.created_at)}</p></div><div className="flex gap-2"><button onClick={() => id && downloadReport(id, 'json')} className="inline-flex items-center gap-2 rounded border border-[#263449] px-3 py-2 text-xs text-gray-300 transition-colors hover:border-cyan-500/60 hover:text-cyan-300"><Download size={13} /> JSON</button><button onClick={() => id && downloadReport(id, 'html')} className="inline-flex items-center gap-2 rounded border border-[#263449] px-3 py-2 text-xs text-gray-300 transition-colors hover:border-cyan-500/60 hover:text-cyan-300"><Download size={13} /> Printable HTML</button></div></header>

    <section className={`relative overflow-hidden rounded border p-5 ${verdictToneBorder(verdict)}`}><div className="absolute inset-y-0 left-0 w-1 bg-current opacity-80" /><div className="grid grid-cols-1 gap-6 lg:grid-cols-[1.2fr_0.8fr_0.8fr_0.8fr]"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-gray-500">Top-level verdict</p><div className="mt-2 flex flex-wrap items-center gap-3"><span className={`text-3xl font-bold uppercase tracking-tight ${verdictTone(verdict)}`}>{verdict}</span><SeverityBadge severity={analysis.severity || verdict} /></div><p className="mt-3 max-w-xl text-sm leading-relaxed text-gray-300">{analysis.summary || 'No executive summary was returned for this investigation.'}</p></div><RiskGauge score={risk} /><ScoreStat label="Evidence confidence" value={analysis.confidence !== undefined ? `${analysis.confidence}%` : 'Unavailable'} help="Represents telemetry completeness and forensic metadata depth, not malice probability." /><ScoreStat label="Investigation status" value={analysis.status || 'Completed'} /></div></section>

    <div className="grid grid-cols-1 gap-5 lg:grid-cols-5"><Panel title="AUTHENTICATION & IDENTITY" open={expanded.authentication} onToggle={() => toggle('authentication')} className="lg:col-span-2"><div className="grid grid-cols-2 gap-3">{(['spf', 'dkim', 'dmarc', 'arc'] as const).map(name => { const item = authentication[name] || {}; return <div key={name} className="rounded border border-[#1C2A3D] bg-[#060A10] p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-gray-500">{name}</p><p className={`mt-2 text-sm font-bold uppercase ${authTone(item.status)}`}>{item.status || 'Missing'}</p>{item.detail && <p className="mt-1 text-[10px] text-gray-600">{item.detail}</p>}</div>; })}</div></Panel><Panel title="THREAT REASONING" open={expanded.reasoning} onToggle={() => toggle('reasoning')} className="lg:col-span-3"><p className="text-sm leading-relaxed text-gray-300">{analysis.extended_reasoning?.summary || analysis.summary || 'No executive reasoning was returned.'}</p><div className="mt-5 grid grid-cols-1 gap-4 md:grid-cols-3"><EvidenceColumn title="Risk-contributing evidence" tone="text-red-400" items={(analysis.risk_breakdown || []).filter((item: any) => item.points > 5).map((item: any) => `${item.reason} (+${item.points})`)} empty="No elevated risk contributors returned." /><EvidenceColumn title="Contextual observations" tone="text-yellow-400" items={(analysis.risk_breakdown || []).filter((item: any) => item.points <= 5).map((item: any) => item.reason)} empty="No contextual observations returned." /><EvidenceColumn title="Informational evidence" tone="text-emerald-400" items={(['spf', 'dkim', 'dmarc'] as const).filter(proto => authentication[proto]?.status === 'pass').map(proto => `${proto.toUpperCase()} alignment verified`)} empty="No informational evidence returned." /></div></Panel></div>

    {attackChain.length > 0 && <Panel title={`ATTACK CHAIN · ${attackChain.length} OBSERVED STAGES`} open={expanded.attackChain} onToggle={() => toggle('attackChain')}><div className="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4">{attackChain.map((step: AnyRecord, index: number) => <div key={`${step.stage}-${index}`} className="relative rounded border border-[#1C2A3D] bg-[#060A10] p-4"><div className="mb-3 flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-full border border-cyan-500/30 bg-cyan-950/30 font-mono text-[10px] text-cyan-300">{String(index + 1).padStart(2, '0')}</span><span className="text-[10px] font-bold uppercase tracking-wider text-gray-500">{step.status || 'Observed'}</span></div><p className="text-sm font-semibold text-gray-200">{step.title || step.stage || 'Unnamed stage'}</p>{Array.isArray(step.evidence) && step.evidence.length > 0 && <ul className="mt-3 space-y-1.5 text-xs text-gray-500">{step.evidence.map((evidence: string, evidenceIndex: number) => <li key={evidenceIndex} className="flex gap-2"><span className="text-cyan-500">•</span>{evidence}</li>)}</ul>}</div>)}</div></Panel>}

    <div className="grid grid-cols-1 gap-5 xl:grid-cols-2"><Panel title={`FORENSIC FINDINGS · ${findings.length}`} open={expanded.findings} onToggle={() => toggle('findings')}><FindingList findings={findings} /></Panel><Panel title={`EXTRACTED IOCs & ARTIFACTS · ${iocs.length}`} open={expanded.iocs} onToggle={() => toggle('iocs')}><IocList iocs={iocs} /></Panel></div>

    {(analysis.threat_intelligence || analysis.threat_intel) && <Panel title="THREAT INTELLIGENCE" open><IntelList data={analysis.threat_intelligence || analysis.threat_intel} /></Panel>}
    {analysis.recommendations && <Panel title="RECOMMENDATIONS" open><div className="grid grid-cols-1 gap-2 md:grid-cols-2">{(Array.isArray(analysis.recommendations) ? analysis.recommendations : [analysis.recommendations]).map((item: any, index: number) => <div key={index} className="flex gap-3 rounded border border-[#1C2A3D] bg-[#060A10] p-3 text-sm text-gray-300"><ListChecks size={16} className="mt-0.5 shrink-0 text-cyan-400" />{typeof item === 'string' ? item : item.text || item.description || JSON.stringify(item)}</div>)}</div></Panel>}
    {(analysis.raw_email || analysis.raw_content) && <Panel title="RAW EMAIL SOURCE" open={expanded.raw} onToggle={() => toggle('raw')}><pre className="max-h-96 overflow-auto whitespace-pre-wrap rounded border border-[#1C2A3D] bg-[#060A10] p-4 font-mono text-[11px] leading-relaxed text-gray-500">{analysis.raw_email || analysis.raw_content}</pre></Panel>}
  </div>;
}

function LoadingState() { return <div className="mx-auto max-w-5xl space-y-4"><div className="h-24 animate-pulse rounded border border-[#151D28] bg-[#080D14]" /><div className="grid grid-cols-3 gap-4"><div className="h-28 animate-pulse rounded border border-[#151D28] bg-[#080D14]" /><div className="col-span-2 h-28 animate-pulse rounded border border-[#151D28] bg-[#080D14]" /></div><p className="font-mono text-xs text-cyan-400 animate-pulse">LOADING FORENSIC ANALYSIS...</p></div>; }
function RiskGauge({ score }: { score: number }) { const tone = score >= 75 ? 'text-red-400' : score >= 40 ? 'text-yellow-400' : 'text-emerald-400'; return <div className="flex flex-col justify-center border-l border-[#1C2A3D] pl-5"><p className="text-[10px] font-bold uppercase tracking-wider text-gray-500">Risk score</p><p className={`mt-1 font-mono text-4xl font-bold ${tone}`}>{score}<span className="text-base text-gray-600"> / 100</span></p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#1C2A3D]"><div className={`h-full rounded-full ${score >= 75 ? 'bg-red-500' : score >= 40 ? 'bg-yellow-500' : 'bg-emerald-500'}`} style={{ width: `${Math.max(0, Math.min(score, 100))}%` }} /></div></div>; }
function ScoreStat({ label, value, help }: { label: string; value: string; help?: string }) { return <div className="border-l border-[#1C2A3D] pl-5"><p className="flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-gray-500">{label}{help && <span title={help}><Info size={11} /></span>}</p><p className="mt-2 text-lg font-semibold text-gray-200">{value}</p></div>; }
function EvidenceColumn({ title, tone, items, empty }: { title: string; tone: string; items: string[]; empty: string }) { return <div><p className={`text-[10px] font-bold uppercase tracking-wider ${tone}`}>{title}</p>{items.length ? <ul className="mt-2 space-y-2 text-xs text-gray-400">{items.map((item, index) => <li key={index} className="flex gap-2"><span className="text-gray-600">•</span>{item}</li>)}</ul> : <p className="mt-2 text-xs text-gray-600">{empty}</p>}</div>; }
function FindingList({ findings }: { findings: AnyRecord[] }) { if (!findings.length) return <Empty text="No deterministic findings were returned." />; return <div className="space-y-2">{findings.map((finding, index) => <div key={`${finding.finding_id || finding.title}-${index}`} className="rounded border border-[#1C2A3D] bg-[#060A10] p-3"><div className="flex items-start justify-between gap-3"><div className="flex gap-2"><ShieldAlert size={15} className="mt-0.5 shrink-0 text-red-400" /><span className="text-sm font-medium text-gray-200">{finding.title || finding.finding_id || 'Finding'}</span></div><SeverityBadge severity={finding.severity || 'info'} /></div><p className="mt-2 pl-6 text-xs leading-relaxed text-gray-500">{finding.description || 'No explanation returned.'}</p></div>)}</div>; }
function IocList({ iocs }: { iocs: AnyRecord[] }) { if (!iocs.length) return <Empty text="No extracted indicators or artifacts were returned." />; return <div className="space-y-4">{(['Actual IOC', 'Infrastructure', 'Forensic Artifact'] as const).map(category => { const categoryIocs = iocs.filter(ioc => categorizeIoc(ioc) === category); if (!categoryIocs.length) return null; return <div key={category}><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider text-gray-500"><span className={`h-2 w-2 rounded-full ${category === 'Actual IOC' ? 'bg-red-400' : category === 'Infrastructure' ? 'bg-yellow-400' : 'bg-cyan-400'}`} />{category} <span className="text-gray-700">{categoryIocs.length}</span></p><div className="mt-2 space-y-1">{categoryIocs.map((ioc, index) => <div key={`${ioc.type}-${ioc.normalized_value || ioc.value}-${index}`} className="flex items-center justify-between gap-3 rounded bg-[#060A10] px-3 py-2"><span className="flex min-w-0 items-center gap-2 font-mono text-xs text-gray-300"><Fingerprint size={13} className="shrink-0 text-gray-600" /><span className="truncate">{ioc.normalized_value || ioc.value}</span></span><span className="shrink-0 rounded border border-[#263449] px-1.5 py-0.5 text-[9px] uppercase text-gray-500">{ioc.type || 'unknown'}</span></div>)}</div></div>; })}</div>; }
function IntelList({ data }: { data: any }) { const records = Array.isArray(data) ? data : Object.entries(data).map(([provider, result]) => ({ provider, result })); return <div className="grid grid-cols-1 gap-2 md:grid-cols-2">{records.map((item: any, index: number) => <div key={index} className="flex items-start justify-between rounded border border-[#1C2A3D] bg-[#060A10] p-3"><div><p className="text-sm font-medium text-gray-200">{item.provider || item.name || 'Provider'}</p><p className="mt-1 text-xs text-gray-500">{typeof item.result === 'string' ? item.result : item.status || JSON.stringify(item.result)}</p></div><ExternalLink size={14} className="text-gray-600" /></div>)}</div>; }
function Empty({ text }: { text: string }) { return <p className="rounded border border-dashed border-[#1C2A3D] p-5 text-center font-mono text-xs text-gray-600">{text}</p>; }
function extractedIocs(analysis: AnyRecord) { if (analysis.extracted_iocs?.iocs) return analysis.extracted_iocs.iocs; if (Array.isArray(analysis.iocs)) return analysis.iocs; return []; }
function formatDate(value?: string) { if (!value) return 'Timestamp unavailable'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString(); }
function verdictTone(verdict: string) { return verdict.toLowerCase() === 'malicious' || verdict.toLowerCase() === 'critical' ? 'text-red-400' : verdict.toLowerCase() === 'suspicious' ? 'text-yellow-400' : 'text-emerald-400'; }
function verdictToneBorder(verdict: string) { return verdict.toLowerCase() === 'malicious' || verdict.toLowerCase() === 'critical' ? 'border-red-500/30 bg-red-950/20' : verdict.toLowerCase() === 'suspicious' ? 'border-yellow-500/30 bg-yellow-950/15' : 'border-emerald-500/25 bg-emerald-950/10'; }
function authTone(status?: string) { return status === 'pass' ? 'text-emerald-400' : status === 'fail' ? 'text-red-400' : 'text-gray-500'; }
