import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { getThreats } from '../services/threatApi';
import { Threat } from '../types';
import { SeverityBadge } from '../components/common/SeverityBadge';
import { Search, Filter, ShieldAlert, ArrowUpRight } from 'lucide-react';

export default function Threats() {
  const [threats, setThreats] = useState<Threat[]>([]); const [loading, setLoading] = useState(true); const [searchTerm, setSearchTerm] = useState(''); const [selectedSeverity, setSelectedSeverity] = useState('ALL'); const [selectedType, setSelectedType] = useState('ALL'); const [selectedStatus, setSelectedStatus] = useState('ALL'); const navigate = useNavigate();
  useEffect(() => { getThreats().then(setThreats).finally(() => setLoading(false)); }, []);
  const filtered = threats.filter(t => (!searchTerm || [t.id, t.target, t.location, t.sender, t.type].some(value => value?.toLowerCase().includes(searchTerm.toLowerCase()))) && (selectedSeverity === 'ALL' || t.severity === selectedSeverity) && (selectedType === 'ALL' || t.type === selectedType) && (selectedStatus === 'ALL' || t.status === selectedStatus));
  return <div className="mx-auto max-w-[1600px] space-y-5"><header className="flex flex-col gap-3 border-b border-[#151D28] pb-5"><div className="flex items-center gap-3"><div className="rounded border border-red-500/20 bg-red-950/20 p-2 text-red-400"><ShieldAlert size={19} /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-red-400">Threat intelligence console</p><h1 className="mt-1 text-2xl font-semibold text-white">Threat investigations</h1></div></div><p className="text-sm text-gray-500">Review observed threats and navigate into the underlying investigation record.</p></header>
    <section className="flex flex-col gap-3 rounded border border-[#151D28] bg-[#080D14] p-4 xl:flex-row xl:items-center"><div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-2.5 text-gray-600" size={15} /><input type="search" placeholder="Search threat ID, target, sender, or location" value={searchTerm} onChange={event => setSearchTerm(event.target.value)} className="w-full rounded border border-[#263449] bg-[#060A10] py-2.5 pl-9 pr-3 text-xs text-gray-200 outline-none placeholder:text-gray-600 focus:border-cyan-500/70" /></div><div className="flex flex-wrap items-center gap-2"><Filter size={14} className="text-gray-600" /><FilterSelect value={selectedSeverity} setValue={setSelectedSeverity} options={['ALL', 'Critical', 'High', 'Medium', 'Low']} label="Severity" /><FilterSelect value={selectedType} setValue={setSelectedType} options={['ALL', 'Credential Theft', 'Phishing', 'BEC', 'Malware', 'Suspicious']} label="Type" /><FilterSelect value={selectedStatus} setValue={setSelectedStatus} options={['ALL', 'Open', 'In Progress', 'Quarantined', 'Resolved']} label="Status" /></div></section>
    <section className="overflow-hidden rounded border border-[#151D28] bg-[#080D14]"><div className="flex items-center justify-between border-b border-[#151D28] px-5 py-4"><div><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-gray-600">Investigation queue</p><p className="mt-1 text-sm text-gray-300"><span className="font-mono text-cyan-400">{filtered.length}</span> matching records</p></div></div>{loading ? <LoadingRows /> : !filtered.length ? <div className="p-12 text-center font-mono text-xs text-gray-600">No threat data matches the selected filters.</div> : <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-xs"><thead className="bg-[#060A10] text-[10px] uppercase tracking-wider text-gray-600"><tr><th className="px-5 py-3">Threat</th><th className="px-4 py-3">Classification</th><th className="px-4 py-3">Severity</th><th className="px-4 py-3">Confidence</th><th className="px-4 py-3">Target</th><th className="px-4 py-3">Last seen</th><th className="px-5 py-3">Status</th><th /></tr></thead><tbody>{filtered.map(threat => <tr key={threat.id} onClick={() => navigate(`/threats/${threat.id}`)} className="cursor-pointer border-t border-[#151D28]/70 transition-colors hover:bg-[#0D1520]"><td className="px-5 py-3"><p className="font-mono font-semibold text-cyan-400">{threat.id}</p><p className="mt-1 max-w-[220px] truncate text-[10px] text-gray-600">{threat.sender || threat.description || 'No sender context'}</p></td><td className="px-4 py-3 text-gray-300">{threat.type}</td><td className="px-4 py-3"><SeverityBadge severity={threat.severity} /></td><td className="px-4 py-3 font-mono text-gray-300">{threat.confidence}%</td><td className="max-w-[180px] truncate px-4 py-3 font-mono text-gray-400">{threat.target}</td><td className="whitespace-nowrap px-4 py-3 text-gray-500">{formatDate(threat.lastSeen)}</td><td className="px-5 py-3"><span className="rounded border border-[#263449] px-2 py-1 text-[10px] font-medium text-gray-400">{threat.status}</span></td><td className="px-3 py-3 text-gray-600"><ArrowUpRight size={14} /></td></tr>)}</tbody></table></div>}</section></div>;
}
function FilterSelect({ value, setValue, options, label }: { value: string; setValue: (value: string) => void; options: string[]; label: string }) { return <select aria-label={label} value={value} onChange={event => setValue(event.target.value)} className="rounded border border-[#263449] bg-[#060A10] px-2.5 py-2 text-xs text-gray-400 outline-none focus:border-cyan-500/70">{options.map(option => <option key={option} value={option}>{option === 'ALL' ? `All ${label}` : option}</option>)}</select>; }
function LoadingRows() { return <div className="space-y-2 p-5">{[1, 2, 3, 4].map(row => <div key={row} className="h-12 animate-pulse rounded bg-[#0D1520]" />)}</div>; }
function formatDate(value: string) { if (!value || value === 'Not reported' || value === 'Unavailable') return 'Not reported by source'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString(); }
